/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MrOscarApplet.java
 *
 * Created on 11/Mar/2009, 18:25:37
 */

package mroscar;

/**
 *
 * @author jld
 */
public class MrOscarApplet extends javax.swing.JApplet {

    /** Initializes the applet MrOscarApplet */
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldQuestion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaReply = new javax.swing.JTextArea();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(mroscar.MrOscarApp.class).getContext().getResourceMap(MrOscarApplet.class);
        jTextFieldQuestion.setText(resourceMap.getString("jTextFieldQuestion.text")); // NOI18N
        jTextFieldQuestion.setName("jTextFieldQuestion"); // NOI18N
        jTextFieldQuestion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldQuestionKeyPressed(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTextAreaReply.setColumns(20);
        jTextAreaReply.setEditable(false);
        jTextAreaReply.setRows(5);
        jTextAreaReply.setFocusable(false);
        jTextAreaReply.setName("jTextAreaReply"); // NOI18N
        jScrollPane1.setViewportView(jTextAreaReply);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
                    .addComponent(jTextFieldQuestion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldQuestionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldQuestionKeyPressed
        if (evt.getKeyChar() == 10) {
            PLCom pl = new PLCom();
            pl.interrogate(jTextFieldQuestion.getText());
            jTextFieldQuestion.setText("");
            jTextAreaReply.append(pl.getResult() + "\n");
        }
    }//GEN-LAST:event_jTextFieldQuestionKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaReply;
    private javax.swing.JTextField jTextFieldQuestion;
    // End of variables declaration//GEN-END:variables

}
